#!/bin/bash
LIVE_USER=$(cat /proc/cmdline | tr ' ' '\n' | grep '^username=' | cut -d= -f2)
[ -z "$LIVE_USER" ] && LIVE_USER="user"

mkdir -p /etc/sddm.conf.d
cat > /etc/sddm.conf << CONF
[Autologin]
User=${LIVE_USER}
Session=plasmawayland
Relogin=true
CONF

cat > /etc/sddm.conf.d/autologin.conf << CONF
[Autologin]
User=${LIVE_USER}
Session=plasmawayland
Relogin=true
CONF
