modules-search: [ local, /usr/lib/calamares/modules ]
sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - netinstall
    - partition
    - users
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - users
    - networkcfg
    - hwclock
    - packages
    - shellselect
    - openrc-setup
    - bootloader
    - grubcfg
    - umount
  - show:
    - finished
branding: borealoس
prompt-install: true
dont-chroot: false
