#!/bin/sh
lb config noauto \
    --distribution trixie \
    --architectures amd64 \
    --binary-images iso-hybrid \
    --debian-installer none \
    --archive-areas "main contrib non-free non-free-firmware" \
    --bootappend-live "boot=live components username=user hostname=BorealOS noeject" \
    --linux-flavours amd64 \
    --iso-application "BorealOS" \
    --iso-publisher "BorealOS" \
    --iso-volume "BorealOS" \
    "${@}"
